
SYM     ::= "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H"
        |   "I" | "J" | "K" | "L" | "M" | "N" | "O" | "P"
        |   "Q" | "R" | "S" | "T" | "U" | "V" | "W" | "X"
        |   "Y" | "Z" | "O";
OP      ::= "and" | "xor" | "or";
unary   ::= "!" OP
        |   "!" parens
        |   "~" OP
        |   "~" parens;
expr    ::= SYM
        |   SYM OP expr;
parens  ::= "(" expr ")";
